version: "3.8"

networks:
  my-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"    
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: password
  backend:
    depends_on:
      - db
    image: demo-express
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    ports:
      - "3000:3000"
    networks:
      - my-network
